export const SHOWALERT="SHOWALERT"
export const HIDEALERT="HIDEALERT"
export const ClEARUSERS="ClEARUSERS"
export const GETREPOS="GETREPOS"
export const GETUSER="GETUSER"
export const SEARCHUSER="SEARCHUSER"
export const SETLOADING="SETLOADING"

